dependencies:
  build:
    - python:3.6.3
    - homebrew:2.1.7

build_targets:
  - name: default
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
      - PYTEST_ADDOPTS="-n auto --cov-config setup.cfg --cov-append --cov-report="
      - COVOPTS="--cov diofant -m \"not slow and not xfail\""
      - PYTHONHASHSEED=0
     
ci:
  builds:
    - name: default
      build_target: default
